/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/super-star-super-mario-bros-c677ff45d94644be9dcf3550e513be30
Title: Super Star (Super Mario Bros)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Estrella(props) {
  const { nodes, materials } = useGLTF("./static/super_star_super_mario_bros.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[62.947, 167.745, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Box001_02_-_Default_0"].geometry}
          material={materials["02_-_Default"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Box001_03_-_Default_0"].geometry}
          material={materials["03_-_Default"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./static/super_star_super_mario_bros.glb");