/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: paethon (https://sketchfab.com/paethon)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/bar-fence-a5863714fcbe4343842d76c2bba21f62
title: Bar Fence
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Fence(props) {
  const { nodes, materials } = useGLTF("./static/bar_fence.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.DefaultMaterial}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./static/bar_fence.glb");