import { handleKeyDown, handleKeyUp, updateCameraMovement } from './cameraControls';
import React, { useState, useRef, useEffect } from 'react';
import { PointerLockControls, Sky } from '@react-three/drei';
import { useFrame, useThree, useEventListener } from "@react-three/fiber";
import { Perf } from 'r3f-perf';
import { useGLTF } from "@react-three/drei";

function Scene1({ onSceneChange }) {
  const handleClick = () => {
    onSceneChange('welcome');
  };

  return (
    <>
    <Model />
    <WallChinese onClick={handleClick}/>
    </>
  );
}

export default Scene1;

export function Model(props) {
  const { nodes, materials } = useGLTF("./static/Historia.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[1.17, 1.11, 0.6]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.004}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
         
          
          
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.EMS_M_EMSBox_0.geometry}
            material={materials.M_EMSBox}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.EMS_M_EMSBox_0001.geometry}
            material={materials.M_EMSBox}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube40_M_Door_0.geometry}
            material={materials.M_Door}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube41_M_GlassDoor_0.geometry}
            material={materials.M_GlassDoor}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube43_M_DoorHandle_0.geometry}
            material={materials.M_DoorHandle}
          />
          <group
            position={[-649.16, 0, -6524.33]}
            rotation={[-Math.PI, 0, -Math.PI]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube40_M_Door_0001.geometry}
              material={materials.M_Door}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube41_M_GlassDoor_0001.geometry}
              material={materials.M_GlassDoor}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube43_M_DoorHandle_0001.geometry}
              material={materials.M_DoorHandle}
            />
          </group>
          <group
            position={[3708.99, 100.12, -392.66]}
            rotation={[0, Math.PI / 2, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube47_M_FFChief_0.geometry}
              material={materials.M_FFChief}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pPlane11_blinn42_0.geometry}
              material={materials.blinn42}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pPlane13_M_Truck_0.geometry}
              material={materials.M_Truck}
            />
          </group>
          <group
            position={[-752.2, 100.12, -614.59]}
            rotation={[-Math.PI, 0, -Math.PI]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube47_M_AccidentInfo_0.geometry}
              material={materials.M_AccidentInfo}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube49_M_Truckinfo_0.geometry}
              material={materials.M_Truckinfo}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pPlane11_M_AccidentScene_0.geometry}
              material={materials.M_AccidentScene}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pPlane15_M_HydrantPhoto_0.geometry}
              material={materials.M_HydrantPhoto}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.IFD_AlarmBell_VRVR_M_AlarmBell_0.geometry}
            material={materials.M_AlarmBell}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.IFD_AlarmBell_VRVR_M_AlarmBell_0001.geometry}
            material={materials.M_AlarmBell}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.IFD_Axe_VRMesh_M_Axe_0.geometry}
            material={materials.M_Axe}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes
                .IFD_CarptenterLight_VRIFD_CarpenterLight_holefix_retopo1_0_bli
                .geometry
            }
            material={materials.blinn26}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.IFD_Chart_VRpolySurface1_M_Chart_0.geometry}
            material={materials.M_Chart}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.IFD_Chart_VRpolySurface1_M_Chart_0001.geometry}
            material={materials.M_Chart}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.IFD_Hydrant_Wrench_VRpolySurface1_M_HydrantWrench_0.geometry
            }
            material={materials.M_HydrantWrench}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.IFD_Hydrant_Wrench_VRpolySurface1_M_HydrantWrench_0001
                .geometry
            }
            material={materials.M_HydrantWrench}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.IFD_Jacket01_VRJacket01_N_retopo1_0_M_Jacket_0.geometry
            }
            material={materials.M_Jacket}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.IFD_Jacket01_VRJacket01_N_retopo1_0_M_Jacket_0001.geometry
            }
            material={materials.M_Jacket}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.IFD_Jacket_VRJacket_N_retopo1_0_M_Jacket1_0.geometry
            }
            material={materials.M_Jacket1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.IFD_Jump_Boots_VRVR_0_M_JumpBoots_0.geometry}
            material={materials.M_JumpBoots}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.IFD_Jump_Boots_VRVR_0_M_JumpBoots_0001.geometry}
            material={materials.M_JumpBoots}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.IFD_LeatherHelmet_M_LeatherHelmet_0.geometry}
            material={materials.M_LeatherHelmet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.IFD_LeatherHelmet_M_LeatherHelmet_0001.geometry}
            material={materials.M_LeatherHelmet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.IFD_LeatherHelmet_M_LeatherHelmet_0002.geometry}
            material={materials.M_LeatherHelmet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes
                .IFD_SodeExtinguisher_VRSodeExtinguisherVE_0_M_SodaExtinguisher
                .geometry
            }
            material={materials.M_SodaExtinguisher}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.IFD_WoodCarvedChair_VRHR_retopo1_0_M_WoodCarvedChair_0
                .geometry
            }
            material={materials.M_WoodCarvedChair}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.IFD_WoodCarvedChair_VRHR_retopo1_0_M_WoodCarvedChair_0001
                .geometry
            }
            material={materials.M_WoodCarvedChair}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.IFD_WoodCarvedChair_VRHR_retopo1_0_M_WoodCarvedChair_0002
                .geometry
            }
            material={materials.M_WoodCarvedChair}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes.IFD_WoodCarvedChair_VRHR_retopo1_0_M_WoodCarvedChair_0003
                .geometry
            }
            material={materials.M_WoodCarvedChair}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube1_M_Limestone_0.geometry}
            material={materials.M_Limestone}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube12_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube13_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube14_M_MainBoard_0.geometry}
            material={materials.M_MainBoard}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube22_M_Trim_0.geometry}
            material={materials.M_Trim}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube23_M_Trim_0.geometry}
            material={materials.M_Trim}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube24_M_Trim_0.geometry}
            material={materials.M_Trim}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube25_M_Trim_0.geometry}
            material={materials.M_Trim}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube28_M_Trim_0.geometry}
            material={materials.M_Trim}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube29_M_Trim_0.geometry}
            material={materials.M_Trim}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube31_M_CeilingPlanks_0.geometry}
            material={materials.M_CeilingPlanks}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube34_M_Trim_0.geometry}
            material={materials.M_Trim}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube35_M_Trim_0.geometry}
            material={materials.M_Trim}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube38_M_Trim_0.geometry}
            material={materials.M_Trim}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube39_M_Trim_0.geometry}
            material={materials.M_Trim}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube42_M_GlassDoor_0.geometry}
            material={materials.M_GlassDoor}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCylinder1_M_IFDLogo_0.geometry}
            material={materials.M_IFDLogo}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlane1_M_Floor_0.geometry}
            material={materials.M_Floor}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlane10_M_ActiveFire_0.geometry}
            material={materials.M_ActiveFire}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlane12_M_GrantFire_0.geometry}
            material={materials.M_GrantFire}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlane14_M_FG_0.geometry}
            material={materials.M_FG}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlane4_M_Wall_0.geometry}
            material={materials.M_Wall}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlane5_M_Wall_0.geometry}
            material={materials.M_Wall}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlane6_M_Wall_0.geometry}
            material={materials.M_Wall}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlane7_M_Wall_0.geometry}
            material={materials.M_Wall}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlane8_M_CeilingBlank_0.geometry}
            material={materials.M_CeilingBlank}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlane9_M_PhotoFireScene_0.geometry}
            material={materials.M_PhotoFireScene}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere1_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube11_M_Limestone_0.geometry}
            material={materials.M_Limestone}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube21_M_EMSBoxInfo_0.geometry}
            material={materials.M_EMSBoxInfo}
          />
          <group position={[-2707.09, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube11_M_Limestone_0001.geometry}
              material={materials.M_Limestone}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube21_M_LeatherHelmetInfo_0.geometry}
              material={materials.M_LeatherHelmetInfo}
            />
          </group>
          <group position={[-98.04, 0, 6483.53]} rotation={[0, Math.PI / 2, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube11_M_Limestone_0007.geometry}
              material={materials.M_Limestone}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube21_M_SodaExtinguisherInfo_0.geometry}
              material={materials.M_SodaExtinguisherInfo}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube44_M_ChartInfo_0.geometry}
              material={materials.M_ChartInfo}
            />
          </group>
          <group position={[-5555.06, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube11_M_Limestone_0002.geometry}
              material={materials.M_Limestone}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube21_M_AxeInfo_0.geometry}
              material={materials.M_AxeInfo}
            />
          </group>
          <group
            position={[-489.88, 0, 1943.8]}
            rotation={[0, -Math.PI / 2, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube21_M_LoungeChair_0.geometry}
              material={materials.M_LoungeChair}
            />
          </group>
          <group
            position={[-489.88, 0, -880.2]}
            rotation={[0, -Math.PI / 2, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube11_M_Limestone_0003.geometry}
              material={materials.M_Limestone}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube21_M_NightPantsInfo_0.geometry}
              material={materials.M_NightPantsInfo}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube45_blinn39_0.geometry}
              material={materials.blinn39}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube46_M_ActiveFire1_0.geometry}
              material={materials.M_ActiveFire1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube48_M_GrantInfo_0.geometry}
              material={materials.M_GrantInfo}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube50_M_FG1_0.geometry}
              material={materials.M_FG1}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube51_M_HydrantPhotoInfo_0.geometry}
              material={materials.M_HydrantPhotoInfo}
            />
          </group>
          <group
            position={[-489.88, 0, -3603.45]}
            rotation={[0, -Math.PI / 2, 0]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube11_M_Limestone_0004.geometry}
              material={materials.M_Limestone}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube21_M_AlarmInfo_0.geometry}
              material={materials.M_AlarmInfo}
            />
          </group>
          <group
            position={[-1373.15, 0, 2547.13]}
            rotation={[Math.PI, 0, Math.PI]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube21_M_JacketInfo_0.geometry}
              material={materials.M_JacketInfo}
            />
          </group>
          <group
            position={[5619.46, 0, 2547.13]}
            rotation={[Math.PI, 0, Math.PI]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube11_M_Limestone_0005.geometry}
              material={materials.M_Limestone}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube21_M_HydrantWrenchInfo_0.geometry}
              material={materials.M_HydrantWrenchInfo}
            />
          </group>
          <group position={[-98.04, 0, 928.48]} rotation={[0, Math.PI / 2, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube11_M_Limestone_0006.geometry}
              material={materials.M_Limestone}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube21_M_BattleLanternInfo_0.geometry}
              material={materials.M_BattleLanternInfo}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./static/Historia.glb");






export function WallChinese(props) {
  const { nodes, materials } = useGLTF("./static/great_wall_survey.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-0.01, 5, 6.28]}
            rotation={[-1.54, 0, 0]}
            scale={0.05}
          >
            <group position={[0, 0, -970.89]} rotation={[-0.03, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#27_0"].geometry}
                material={materials.Material_27}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#27_0_1"].geometry}
                material={materials.Material_27}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#32_0"].geometry}
                material={materials.Material_32}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#32_0_1"].geometry}
                material={materials.Material_32}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#32_0_2"].geometry}
                material={materials.Material_32}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#31_0"].geometry}
                material={materials.Material_31}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#31_0_1"].geometry}
                material={materials.Material_31}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#31_0_2"].geometry}
                material={materials.Material_31}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#31_0_3"].geometry}
                material={materials.Material_31}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#31_0_4"].geometry}
                material={materials.Material_31}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#31_0_5"].geometry}
                material={materials.Material_31}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#31_0_6"].geometry}
                material={materials.Material_31}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_1"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_2"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_3"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_4"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_5"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_6"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_7"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_8"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_9"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_10"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_11"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_12"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_13"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_14"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_15"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_16"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_17"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_18"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_19"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_20"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_21"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_22"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_23"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_24"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_25"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_26"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_27"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_28"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_29"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_30"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_31"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#28_0_32"].geometry}
                material={materials.Material_28}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_1"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_2"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_3"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_4"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_5"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_6"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_7"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_8"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_9"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_10"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_11"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_12"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_13"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_14"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_15"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_16"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_17"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_18"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_19"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_20"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_21"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_22"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_23"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_24"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_25"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_26"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#30_0_27"].geometry}
                material={materials.Material_30}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#29_0"].geometry}
                material={materials.Material_29}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#29_0_1"].geometry}
                material={materials.Material_29}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#29_0_2"].geometry}
                material={materials.Material_29}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#29_0_3"].geometry}
                material={materials.Material_29}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#29_0_4"].geometry}
                material={materials.Material_29}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#29_0_5"].geometry}
                material={materials.Material_29}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#29_0_6"].geometry}
                material={materials.Material_29}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#29_0_7"].geometry}
                material={materials.Material_29}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#29_0_8"].geometry}
                material={materials.Material_29}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["DefaultName_Material_#29_0_9"].geometry}
                material={materials.Material_29}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./static/great_wall_survey.glb");