/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Thomas Flynn (https://sketchfab.com/nebulousflynn)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/jardiniere-and-stand-poole-museum-a6e29dff01ba4c57aa230016f2e9e4b2
title: Jardinière and stand, Poole Museum
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Vase3(props) {
  const { nodes, materials } = useGLTF(
    "./static/jardiniere_and_stand_poole_museum.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.main}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.main}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./static/jardiniere_and_stand_poole_museum.glb");